model = "gpt-5.4"
model_reasoning_effort = "medium"
personality = "pragmatic"
web_search = "cached"

[analytics]
enabled = false

[feedback]
enabled = false

[mcp_servers.deepwiki]
url = "https://mcp.deepwiki.com/mcp"

[mcp_servers.context7]
args = [
    "x",
    "--",
    "npx",
    "@upstash/context7-mcp",
]
command = "mise"

[tui]
animations = true
show_tooltips = false
