#!/bin/bash

. $(dirname "$0")/utility.sh

if ! type_exists brew; then
    # See: https://github.com/Homebrew/install
    /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
fi
