#!/bin/bash
#
# Prerequisite
#   - brew command
#
# You can search from https://formulae.brew.sh/

. $(dirname "$0")/utility.sh

# Install a Homebrew formula
install_cask_if_needed() {
    if ! brew_cask_exists ${1}; then
        info "Installing: ${1}"
        brew install ${1}
    fi
}

# Make sure we’re using the latest Homebrew.
brew update

# Upgrade any already-installed formulae.
brew upgrade




# Apps
# General
install_cask_if_needed firefox
install_cask_if_needed brave-browser
install_cask_if_needed google-chrome
install_cask_if_needed cleanshot
install_cask_if_needed cleanmymac
install_cask_if_needed raycast
install_cask_if_needed notion
install_cask_if_needed obsidian
install_cask_if_needed slack
install_cask_if_needed divvy
install_cask_if_needed spotify
install_cask_if_needed deepl

# Dev
install_cask_if_needed iterm2
install_cask_if_needed fig
install_cask_if_needed visual-studio-code

# CLI
# https://developer.1password.com/docs/cli/get-started/
install_cask_if_needed 1password/tap/1password-cli


# Font
# https://github.com/ryanoasis/nerd-fonts
if ! brew_cask_exists font-fira-code-nerd-font; then
    info "Installing: font-fira-code-nerd-font"
    brew tap homebrew/cask-fonts
    brew install --cask font-fira-code-nerd-font
fi




# Remove outdated versions from the cellar
brew cleanup

# Check system potential problem
brew doctor