#!/bin/bash

# Install tools using omebrew Cask
# See: https://github.com/Homebrew/homebrew-cask

# Apps
brew cask install google-japanese-ime
brew cask install 1password
brew cask install dropbox
brew cask install google-chrome
brew cask install firefox
brew cask install chromedriver
brew cask install iterm2
brew cask install visual-studio-code
brew cask install jetbrains-toolbox
brew cask install docker
brew cask install kitty
brew cask install divvy
brew cask install notion
brew cask install superhuman
brew cask install slack
brew cask install toggl
brew cask install spotify
brew cask install zoomus

# Fonts
brew tap homebrew/cask-fonts
brew cask install font-hack-nerd-font
