#!/bin/bash

. $(dirname "$0")/utility.sh

# Prerequisites
if ! brew_formula_exists fish; then
    warning "Missing fish. Install fish first"
fi

if ! type_exists omf; then
    # See: https://github.com/oh-my-fish/oh-my-fish#installation
    curl https://raw.githubusercontent.com/oh-my-fish/oh-my-fish/master/bin/install | fish
fi


info "omf doctor"
omf doctor