#!/bin/bash
#
# Usage

#######################################
# Usage
# Arguments:
#   None
# Returns:
#   None
#######################################
run_usage() {

cat <<EOT

Usage: $(basename "$0") <command>

Commands:
    run        Run the command
    update      Pull the latest changes to update
EOT

}
