#!/bin/bash
#
# Utilities

#######################################
# Install xcode-select 
#######################################
install_xcode_select() {
  if ! type xcode-select >&- && xpath=$( xcode-select --print-path ) && test -d "${xpath}" && test -x "${xpath}"; then
    info "Installing xcode-select"
    xcode-select --install
  else
    success "Done. xcode-select already installed"
  fi
}

#######################################
# Install Homebrew
#######################################
install_homebrew() {
  if ! type_exists "brew"; then
    info "Installing homebrew"
    /usr/bin/ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"
  else
    success "Done. homebrew already installed"
  fi
}

#######################################
# Install Homebrew fomulas
#######################################
install_homebrew_fomulas() {
  if type_exists "brew"; then
    bash $DOTFILES_DIRECTORY/lib/brew.sh &> /dev/null
    bash $DOTFILES_DIRECTORY/lib/brew-cask.sh &> /dev/null
}

#######################################
# Usage
#######################################
usage() {
cat <<EOT
Usage: $(basename "$0") <command>

Commands:
    bootstrap   Setup
    update      Pull the latest changes
EOT
  RETVAL="2"
}