[tools]
# Programming Languages
java   = "latest"
node   = "lts"
pnpm   = "latest"
python = "latest"
rust   = "latest"
bun    = "latest"

# NPM Global Packages
"npm:trash-cli"    = "latest"
"npm:defuddle-cli" = "latest"
"npm:sfw"          = "latest"
