[tools]
# Programming Languages
java   = "latest"
node   = "lts"
pnpm   = "latest"
python = "3.13"
rust   = "latest"

# Ruby Gems
"gem:cocoapods" = "latest"

# NPM Global Packages
"npm:trash-cli"    = "latest"
"npm:defuddle-cli" = "latest"
"npm:sfw"          = "latest"
